### PR TITLE
Added portuguese-brazil (pt-br) locale

### PR DESCRIPTION
**Pull request by adammacias**

### CODE REVIEW

**Comment by matchu** [comment]
Oh, cool! :D It'll probs be a while before my personal schedule allows me
to sit down and deploy this new version, but, exciting! I'll keep it on my
todo list :) Thanks!

**Comment by adammacias** [comment]
:up: @matchu :dancers:

**Comment by matchu** [comment]
Thanks for the ping :)

**Comment by matchu** [comment]
Just went out in 1.7.0; watch your extension list for the update to roll out :) Thanks for your help! :D

**Comment by adammacias** [comment]
Okay, no problem! :yum:

**Pull request merged**
